using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Lavaland.OrePoints;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Lavaland.OrePoints.UI;

[GenerateTypedNameReferences]
public sealed partial class OrePointsShopWindow : FancyWindow
{
    public event Action<string>? OnBuyPressed;

    public OrePointsShopWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("ore-points-shop-title");
    }

    public void UpdateBalance(int balance)
    {
        BalanceLabel.Text = $"{balance} ОР";
    }

    public void Populate(List<OrePointsShopEntryState> entries, int balance)
    {
        UpdateBalance(balance);
        ItemsContainer.RemoveAllChildren();

        var odd = false;
        foreach (var entry in entries)
        {
            var panel = new PanelContainer
            {
                HorizontalExpand = true,
            };
            if (odd)
                panel.StyleClasses.Add("PanelDark");
            odd = !odd;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                HorizontalExpand = true,
                Margin = new Thickness(4, 2, 4, 2),
            };

            var icon = new EntityPrototypeView
            {
                MinSize = new Vector2(32, 32),
                SetSize = new Vector2(32, 32),
                VerticalAlignment = VAlignment.Center,
            };
            icon.SetPrototype(entry.ItemId);

            var nameLabel = new Label
            {
                Text = entry.Name,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                ClipText = true,
            };

            var costLabel = new Label
            {
                Text = $"{entry.Cost} ОР",
                VerticalAlignment = VAlignment.Center,
                MinSize = new Vector2(54, 0),
            };

            var buyButton = new Button
            {
                Text = Loc.GetString("ore-points-shop-buy-button"),
                Disabled = false,
                VerticalAlignment = VAlignment.Center,
                MinSize = new Vector2(60, 0),
            };

            var id = entry.ItemId;
            buyButton.OnPressed += _ => OnBuyPressed?.Invoke(id);

            row.AddChild(icon);
            row.AddChild(nameLabel);
            row.AddChild(costLabel);
            row.AddChild(buyButton);
            panel.AddChild(row);
            ItemsContainer.AddChild(panel);
        }
    }
}
