- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: CrewSkills
      skills:
      - skillBotany #base
      - skillBaseMed
      - skillBaseConstraction

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: ClownPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
