using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Chaplain;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Content.Shared.Dataset;

namespace Content.Client.Imperial.Chaplain;

/// <summary>
/// Выбор названия религии, имени божества и названия библии верховным жрецом
/// (поля «Название религии», «Имя божества», «Название библии» из настроек персонажа SS13).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ImperialReligionSetupWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IRobustRandom _random = default!;

    private static readonly ProtoId<DatasetPrototype> ReligionNames = "ImperialReligionNames";

    public event Action<string, string, string>? OnSubmit;

    private bool _submitted;

    public ImperialReligionSetupWindow(string religion, string deity, string bible)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var edit in new[] { ReligionEdit, DeityEdit, BibleEdit })
        {
            edit.IsValid = text => text.Length <= ImperialBibleSkins.MaxNameLength;
        }

        ReligionEdit.Text = religion;
        DeityEdit.Text = deity;
        BibleEdit.Text = bible;

        RandomReligionButton.OnPressed += _ =>
        {
            if (_proto.TryIndex(ReligionNames, out var names) && names.Values.Count > 0)
                ReligionEdit.Text = _random.Pick(names.Values);
        };
        ConfirmButton.OnPressed += _ => Close();
        OnClose += Submit;
    }

    /// <summary>Закрытие окна тоже подтверждает выбор, как и настройки по умолчанию в SS13.</summary>
    private void Submit()
    {
        if (_submitted)
            return;

        _submitted = true;
        OnSubmit?.Invoke(ReligionEdit.Text, DeityEdit.Text, BibleEdit.Text);
    }
}
