using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Imperial.Chaplain;

/// <summary>
/// Приглашение вступить в религию станции (tgui_alert из invite_deacon в SS13).
/// Закрытие окна или истечение 60 секунд считается отказом.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ImperialDeaconInviteWindow : FancyWindow
{
    private static readonly TimeSpan Timeout = TimeSpan.FromSeconds(60);

    public event Action<bool>? OnAnswer;

    private bool _answered;
    private TimeSpan _elapsed;

    public ImperialDeaconInviteWindow(string deity)
    {
        RobustXamlLoader.Load(this);

        MessageLabel.SetMessage(Loc.GetString("imperial-deaconize-invite-text", ("deity", deity)));
        YesButton.OnPressed += _ => Answer(true);
        NoButton.OnPressed += _ => Answer(false);
        OnClose += () => Answer(false);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _elapsed += TimeSpan.FromSeconds(args.DeltaSeconds);
        if (_elapsed >= Timeout)
            Close();
    }

    private void Answer(bool accepted)
    {
        if (_answered)
            return;

        _answered = true;
        OnAnswer?.Invoke(accepted);
        Close();
    }
}
