using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.BSA;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Imperial.BSA.UI;

[GenerateTypedNameReferences]
public sealed partial class BSAConsoleWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private BSAUIState? _lastState;
    private bool _updating; // подавляет события списка во время UpdateState

    public event Action? OnFire;
    public event Action? OnScan;
    public event Action<NetEntity?>? OnSelectTarget;

    private NetEntity? _selectedBeacon;

    public BSAConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        FireButton.OnPressed += _ => OnFire?.Invoke();
        ScanButton.OnPressed += _ => OnScan?.Invoke();

        BeaconList.OnItemSelected += args =>
        {
            if (_updating) return;
            if (args.ItemIndex < 0 || _lastState == null)
                return;
            if (args.ItemIndex >= _lastState.AvailableBeacons.Count)
                return;

            var beacon = _lastState.AvailableBeacons[args.ItemIndex].Uid;
            _selectedBeacon = beacon;
            OnSelectTarget?.Invoke(beacon);
        };

        BeaconList.OnItemDeselected += _ =>
        {
            if (_updating) return;
            _selectedBeacon = null;
            OnSelectTarget?.Invoke(null);
        };
    }

    public void UpdateState(BSAUIState state)
    {
        _lastState = state;

        // Питание
        PowerStatus.SetMarkup(state.Powered
            ? $"[color=lime]{Loc.GetString("bsa-yes")}[/color]"
            : $"[color=red]{Loc.GetString("bsa-no")}[/color]");

        // Визуальное состояние частей
        BackPartControl.SetExists(state.BackPartExists);
        FrontPartControl.SetExists(state.FrontPartExists);
        // ConsolePartControl всегда exists (AlwaysExists=True)

        // Кнопка сканирования активна только при наличии питания
        ScanButton.Disabled = !state.Powered;

        // Список маяков
        _updating = true;
        BeaconList.Clear();
        var beacons = state.AvailableBeacons;
        for (var i = 0; i < beacons.Count; i++)
        {
            var (uid, name) = beacons[i];
            BeaconList.AddItem(name);
            if (uid == state.SelectedTarget)
            {
                BeaconList[i].Selected = true;
                _selectedBeacon = uid;
            }
        }
        if (state.SelectedTarget == null)
            _selectedBeacon = null;
        _updating = false;

        // Кнопка выстрела
        FireButton.Disabled = !state.CanFire;

        // Перезарядка
        if (state.NextFire != null)
        {
            var remaining = state.NextFire.Value - _timing.CurTime;
            if (remaining > TimeSpan.Zero)
            {
                var secs = (int)Math.Ceiling(remaining.TotalSeconds);
                CooldownLabel.SetMarkup($"[color=orange]{secs}s[/color]");
            }
            else
            {
                CooldownLabel.SetMarkup($"[color=lime]{Loc.GetString("bsa-ready")}[/color]");
            }
        }
        else
        {
            CooldownLabel.SetMarkup($"[color=lime]{Loc.GetString("bsa-ready")}[/color]");
        }
    }
}

/// <summary>
/// Отображает иконку части BSA — серая/потухшая если отсутствует, цветная если на месте.
/// Использует PA RSI файлы: control_box, end_cap, power_box.
/// </summary>
public sealed class BSAPartControl : Control
{
    private static readonly ProtoId<ShaderPrototype> GreyscaleShaderId = "Greyscale";
    private readonly ShaderInstance _greyShader;
    private readonly TextureRect _icon;

    /// <summary>Имя RSI файла без расширения (например "power_box").</summary>
    public string PartRsi { get; set; } = "control_box";

    /// <summary>Если true — часть всегда считается установленной (консоль).</summary>
    public bool AlwaysExists { get; set; } = false;

    public BSAPartControl()
    {
        _greyShader = IoCManager.Resolve<IPrototypeManager>()
            .Index(GreyscaleShaderId).Instance();

        AddChild(_icon = new TextureRect
        {
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
        });
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        var cache = IoCManager.Resolve<IResourceCache>();
        var rsi = cache.GetResource<RSIResource>(
            $"/Textures/Structures/Power/Generation/PA/{PartRsi}.rsi").RSI;
        MinSize = (Vector2i) rsi.Size * 2; // ×2 чтобы было крупнее
        _icon.Texture = rsi["completed"].Frame0;
        SetExists(AlwaysExists);
    }

    public void SetExists(bool exists)
    {
        if (exists)
        {
            _icon.ShaderOverride = null;
            _icon.ModulateSelfOverride = null;
        }
        else
        {
            _icon.ShaderOverride = _greyShader;
            _icon.ModulateSelfOverride = new Color(100, 100, 100);
        }
    }
}
