using System.Collections.Generic;
using System.Numerics;
using Content.Client.Imperial.UI.Windows.BaseImperialWindow;
using Content.Shared.Imperial.XxRaay.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Network;
using Robust.Client.GameObjects;

namespace Content.Client.Imperial.XxRaay.UI;

[GenerateTypedNameReferences]
public sealed partial class AnimatronicControllerWindow : BaseImperialWindow
{
	[Dependency] private readonly IEntityManager _entityManager = default!;

	public event Action<NetEntity, NetEntity>? OnAnimatronicWaypointSelected;
	public event Action<NetEntity>? OnAnimatronicClearTarget;
	public event Action<NetEntity>? OnAnimatronicObserving;

	private Dictionary<NetEntity, PanelContainer> _animCards = new();
	private Dictionary<NetEntity, Color> _buttonOriginalColors = new();

	public AnimatronicControllerWindow()
	{
		RobustXamlLoader.Load(this);
		IoCManager.InjectDependencies(this);
	}

	public void UpdateState(AnimDataStateEvent state)
	{
		var animScrollContainer = Contents.GetChild(0) as ScrollContainer;
		var animList = animScrollContainer?.GetChild(0) as BoxContainer;

		animList?.RemoveAllChildren();
		_animCards.Clear();
		_buttonOriginalColors.Clear();

		foreach (var anim in state.Animatronics)
		{
			var card = CreateAnimatronicCard(anim, state.Waypoints);
			animList?.AddChild(card);
			_animCards[anim.Entity] = card;
		}
	}

	private PanelContainer CreateAnimatronicCard(AnimDto anim, List<WaypointDto> waypoints)
	{
		var card = new PanelContainer
		{
			StyleClasses = { "AngleRectPass" },
			HorizontalExpand = true,
			Margin = new Thickness(0, 0, 0, 5)
		};

		var cardContent = new BoxContainer
		{
			Orientation = BoxContainer.LayoutOrientation.Horizontal,
			Margin = new Thickness(10, 10, 10, 10),
			SeparationOverride = 0,
			HorizontalExpand = true
		};

		var spritePanel = new PanelContainer
		{
			PanelOverride = new StyleBoxFlat
			{
				BackgroundColor = Color.FromHex("#2A2A2A")
			},
			VerticalExpand = true
		};

		var spriteView = new SpriteView
		{
			OverrideDirection = Direction.South,
			Scale = new Vector2(5f, 5f),
			SetSize = new Vector2(96, 96),
			Margin = new Thickness(5, 5, 5, 5),
			VerticalExpand = true,
			VerticalAlignment = VAlignment.Center
		};

		var entity = _entityManager.GetEntity(anim.Entity);
		if (entity.Valid)
		{
			spriteView.SetEntity(entity);
		}

		spritePanel.AddChild(spriteView);

		var nameStatusPanel = new PanelContainer
		{
			PanelOverride = new StyleBoxFlat
			{
				BackgroundColor = Color.FromHex("#333333")
			},
			HorizontalExpand = true,
			VerticalExpand = true
		};

		var nameStatusContent = new BoxContainer
		{
			Orientation = BoxContainer.LayoutOrientation.Horizontal,
			Margin = new Thickness(5, 5, 5, 5),
			SeparationOverride = 10,
			HorizontalExpand = true
		};

		var nameStatusContainer = new BoxContainer
		{
			Orientation = BoxContainer.LayoutOrientation.Vertical,
			VerticalExpand = true,
			VerticalAlignment = VAlignment.Center
		};

		var nameLabel = new Label
		{
			Text = anim.DisplayName,
			StyleClasses = { "LabelSubTextPassExtraBoldServerName" },
			ModulateSelfOverride = Color.White
		};

		var statusContainer = new BoxContainer
		{
			Orientation = BoxContainer.LayoutOrientation.Horizontal,
			SeparationOverride = 3
		};

		if (anim.CurrentWaypointId != null)
		{
			var dotsLabel = new Label
			{
				Text = Loc.GetString("animatronic-controller-waypoint-separator"),
				StyleClasses = { "LabelSubTextPassMediumBuy" },
				ModulateSelfOverride = Color.FromHex("#FFD700"), 
				VerticalAlignment = VAlignment.Center,
				Margin = new Thickness(0, 0, 3, 0)
			};

			var waypointLabel = new Label
			{
				Text = anim.CurrentWaypointId,
				StyleClasses = { "LabelSubTextPassMediumBuy" },
				ModulateSelfOverride = Color.FromHex("#FFD700"), 
				VerticalAlignment = VAlignment.Center
			};

			statusContainer.AddChild(dotsLabel);
			statusContainer.AddChild(waypointLabel);
		}
		else
		{
			var statusLabel = new Label
			{
				Text = Loc.GetString("animatronic-controller-status-idle"),
				StyleClasses = { "LabelSubTextPassMediumBuy" },
				ModulateSelfOverride = Color.FromHex("#888888")
			};
			statusContainer.AddChild(statusLabel);
		}

		nameStatusContainer.AddChild(nameLabel);
		nameStatusContainer.AddChild(statusContainer);

		var waypointButtonsContent = new BoxContainer
		{
			Orientation = BoxContainer.LayoutOrientation.Horizontal,
			SeparationOverride = 5,
			HorizontalExpand = true
		};

		var waypointGrid = new GridContainer
		{
			Columns = 2,
			HorizontalExpand = true
		};

		foreach (var wp in waypoints)
		{
			var isActive = anim.CurrentWaypointId == wp.WaypointId;
			var wpButton = new Button
			{
				Text = wp.WaypointId,
				HorizontalExpand = true
			};

			var originalColor = isActive ? Color.FromHex("#4CAF50") : Color.FromHex("#888888");
			_buttonOriginalColors[wp.Entity] = originalColor;
			wpButton.ModulateSelfOverride = originalColor;

			wpButton.StyleClasses.Add("ButtonOpenBoth");

			var animEntity = anim.Entity;
			var wpEntity = wp.Entity;

			wpButton.OnPressed += _ =>
			{
				OnAnimatronicWaypointSelected?.Invoke(animEntity, wpEntity);
			};

			wpButton.OnMouseEntered += _ =>
			{
				if (!isActive)
					wpButton.ModulateSelfOverride = Color.FromHex("#AAAAAA");
			};

			wpButton.OnMouseExited += _ =>
			{
				if (!isActive && _buttonOriginalColors.TryGetValue(wpEntity, out var original))
					wpButton.ModulateSelfOverride = original;
			};

			waypointGrid.AddChild(wpButton);
		}

		var buttonsContainer = new BoxContainer
		{
			Orientation = BoxContainer.LayoutOrientation.Vertical,
			SeparationOverride = 5,
			VerticalExpand = true
		};

		var clearButton = new Button
		{
			Text = Loc.GetString("animatronic-controller-button-clear"),
			StyleClasses = { "ButtonOpenBoth" },
			ModulateSelfOverride = Color.FromHex("#FF4444"),
			VerticalExpand = true,
			HorizontalExpand = true
		};

		var clearButtonOriginalColor = Color.FromHex("#FF4444");
		var animEntityForClear = anim.Entity;
		clearButton.OnPressed += _ =>
		{
			OnAnimatronicClearTarget?.Invoke(animEntityForClear);
		};

		clearButton.OnMouseEntered += _ =>
		{
			clearButton.ModulateSelfOverride = Color.FromHex("#FF6666");
		};

		clearButton.OnMouseExited += _ =>
		{
			clearButton.ModulateSelfOverride = clearButtonOriginalColor;
		};

		var observingButton = new Button
		{
			Text = Loc.GetString("animatronic-controller-button-observing"),
			StyleClasses = { "ButtonOpenBoth" },
			ModulateSelfOverride = Color.FromHex("#4A90E2"),
			VerticalExpand = true,
			HorizontalExpand = true
		};

		var observingButtonOriginalColor = Color.FromHex("#4A90E2");
		var animEntityForObserving = anim.Entity;
		observingButton.OnPressed += _ =>
		{
			OnAnimatronicObserving?.Invoke(animEntityForObserving);
		};

		observingButton.OnMouseEntered += _ =>
		{
			observingButton.ModulateSelfOverride = Color.FromHex("#6BA3E8");
		};

		observingButton.OnMouseExited += _ =>
		{
			observingButton.ModulateSelfOverride = observingButtonOriginalColor;
		};

		buttonsContainer.AddChild(clearButton);
		buttonsContainer.AddChild(observingButton);

		waypointButtonsContent.AddChild(waypointGrid);
		waypointButtonsContent.AddChild(buttonsContainer);

		nameStatusContent.AddChild(nameStatusContainer);
		nameStatusContent.AddChild(waypointButtonsContent);
		nameStatusPanel.AddChild(nameStatusContent);

		cardContent.AddChild(spritePanel);
		cardContent.AddChild(nameStatusPanel);
		card.AddChild(cardContent);

		return card;
	}
}
