using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Lavaland.OrePoints.MiningVoucher.UI;

[GenerateTypedNameReferences]
public sealed partial class MiningVoucherWindow : FancyWindow
{
    public event Action<int>? OnKitSelected;

    private static readonly (string Name, string Description, string[] Items)[] Kits =
    {
        (
            Loc.GetString("mining-voucher-kit-survival-name"),
            Loc.GetString("mining-voucher-kit-survival-desc"),
            new[] { "ClothingBeltMiningWebbing", "RescueCapsule" }
        ),
        (
            Loc.GetString("mining-voucher-kit-fulton-name"),
            Loc.GetString("mining-voucher-kit-fulton-desc"),
            new[] { "FultonBeacon", "Fulton" }
        ),
        (
            Loc.GetString("mining-voucher-kit-plasma-name"),
            Loc.GetString("mining-voucher-kit-plasma-desc"),
            new[] { "OreBagMining", "WeaponPlasmaCutter" }
        ),
        (
            Loc.GetString("mining-voucher-kit-crusher-name"),
            Loc.GetString("mining-voucher-kit-crusher-desc"),
            new[] { "WeaponKineticCrusher", "FireExtinguisherMini" }
        ),
        (
            Loc.GetString("mining-voucher-kit-backpack-name"),
            Loc.GetString("mining-voucher-kit-backpack-desc"),
            new[] { "OreBag", "FlashlightSecliteMining", "MiningMedipen", "SurvivalKnife" }
        ),
    };

    public MiningVoucherWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("mining-voucher-title");
        PopulateKits();
    }

    private void PopulateKits()
    {
        KitsContainer.RemoveAllChildren();

        var odd = false;
        for (var i = 0; i < Kits.Length; i++)
        {
            var (kitName, kitDesc, items) = Kits[i];

            var panel = new PanelContainer
            {
                HorizontalExpand = true,
            };
            if (odd)
                panel.StyleClasses.Add("PanelDark");
            odd = !odd;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                HorizontalExpand = true,
                Margin = new Thickness(4, 4, 4, 4),
            };

            // Item icons row
            var iconsBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 2,
                VerticalAlignment = VAlignment.Center,
            };
            foreach (var itemId in items)
            {
                var icon = new EntityPrototypeView
                {
                    MinSize = new Vector2(32, 32),
                    SetSize = new Vector2(32, 32),
                    VerticalAlignment = VAlignment.Center,
                };
                icon.SetPrototype(itemId);
                iconsBox.AddChild(icon);
            }

            var nameLabel = new Label
            {
                Text = kitName,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                ClipText = true,
                ToolTip = kitDesc,
            };

            var kitIndex = i;
            var selectButton = new Button
            {
                Text = Loc.GetString("mining-voucher-select-button"),
                VerticalAlignment = VAlignment.Center,
                MinSize = new Vector2(80, 0),
            };
            selectButton.OnPressed += _ =>
            {
                OnKitSelected?.Invoke(kitIndex);
                Close();
            };

            row.AddChild(iconsBox);
            row.AddChild(nameLabel);
            row.AddChild(selectButton);
            panel.AddChild(row);
            KitsContainer.AddChild(panel);
        }
    }
}
