using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Linq;
using System.Threading;
namespace Content.Client.Imperial.CustomChaplain.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GodSelectionWindow : DefaultWindow
    {
        private string? _selectedPredefinedGod;
        private string? _customGodName;
        private bool _isCustomMode;
        private CancellationTokenSource? _resetCts;

        public event Action<string, bool>? OnGodSelected;

        public GodSelectionWindow()
        {
            RobustXamlLoader.Load(this);

            // Initialize predefined gods dropdown
            PredefinedGodsDropdown.AddItem(Loc.GetString("god-selection-cthulhu-button"), 0);
            PredefinedGodsDropdown.AddItem(Loc.GetString("god-selection-honk-mother-button"), 1);
            PredefinedGodsDropdown.AddItem(Loc.GetString("god-selection-technomium-button"), 2);
            PredefinedGodsDropdown.AddItem(Loc.GetString("god-selection-gray-wave-button"), 3);

            _selectedPredefinedGod = GetPredefinedGodName(0);

            // Subscribe to events
            PredefinedGodsDropdown.OnItemSelected += OnPredefinedGodSelected;
            CustomGodButton.OnPressed += OnCustomGodClicked;
            ConfirmButton.OnPressed += OnConfirmClicked;
            CustomGodTextBox.OnTextChanged += OnCustomGodTextChanged;

            // Subscribe to window closing event
            this.OnClose += OnWindowClosing;

            // Set initial state
            UpdateUI();
        }

        private void OnWindowClosing()
        {
            ResetState();
        }

        private void OnPredefinedGodSelected(OptionButton.ItemSelectedEventArgs args)
        {
            _selectedPredefinedGod = GetPredefinedGodName(args.Id);
            _isCustomMode = false;
            _customGodName = null;

            // Обновляем визуальное состояние dropdown
            PredefinedGodsDropdown.SelectId(args.Id);

            // Не очищаем текстовое поле - пользователь может хотеть переключаться между опциями
            UpdateUI();
        }

        private void OnCustomGodClicked(BaseButton.ButtonEventArgs args)
        {
            var customName = CustomGodTextBox.Text.Trim();
            if (string.IsNullOrEmpty(customName))
            {
                StatusText.Text = Loc.GetString("god-selection-enter-god-name");
                return;
            }

            // Валидация длины и недопустимых символов
            if (customName.Length > 32)
            {
                StatusText.Text = Loc.GetString("god-selection-name-too-long");
                return;
            }

            if (customName.Any(char.IsControl))
            {
                StatusText.Text = Loc.GetString("god-selection-invalid-characters");
                return;
            }

            _customGodName = customName;
            _isCustomMode = true;
            _selectedPredefinedGod = null;
            // Не вызываем ClearDropdownSelection() - это сбросит к предопределенному богу
            // Просто оставляем dropdown как есть, но внутреннее состояние указывает на custom режим
            UpdateUI();
        }

        private void OnCustomGodTextChanged(LineEdit.LineEditEventArgs args)
        {
            // Clear custom mode if user starts typing after selecting predefined
            if (!_isCustomMode || !string.IsNullOrWhiteSpace(args.Text))
                return;

            _customGodName = null;
            _isCustomMode = false;
            UpdateUI();
        }

        private void OnConfirmClicked(BaseButton.ButtonEventArgs args)
        {
            switch (_isCustomMode)
            {
                case true when !string.IsNullOrEmpty(_customGodName):
                    OnGodSelected?.Invoke(_customGodName, true);
                    Close();
                    break;
                case false when !string.IsNullOrEmpty(_selectedPredefinedGod):
                    OnGodSelected?.Invoke(_selectedPredefinedGod, false);
                    Close();
                    break;
            }
        }

        private void UpdateUI()
        {
            var godName = _isCustomMode ? _customGodName : _selectedPredefinedGod;
            var hasSelection = (_isCustomMode && !string.IsNullOrEmpty(_customGodName)) ||
                               (!_isCustomMode && !string.IsNullOrEmpty(_selectedPredefinedGod));

            ConfirmButton.Disabled = !hasSelection;

            if (hasSelection && !string.IsNullOrEmpty(godName))
            {
                StatusText.Text = Loc.GetString("god-selection-ready-to-confirm", ("godName", godName));
            }
            else
            {
                StatusText.Text = Loc.GetString("god-selection-choose-god");
            }
        }

        private void ResetState()
        {
            _resetCts?.Cancel();
            _resetCts = null;

            _selectedPredefinedGod = null;
            _customGodName = null;
            _isCustomMode = false;
            ClearDropdownSelection();
            CustomGodTextBox.Text = "";
            UpdateUI();
        }

        private void ClearDropdownSelection()
        {
            // Возвращаем к первому элементу и устанавливаем его как выбранный
            PredefinedGodsDropdown.SelectId(0);
            _selectedPredefinedGod = GetPredefinedGodName(0);
            _isCustomMode = false;
        }

        private static string GetPredefinedGodName(int id)
        {
            return id switch
            {
                0 => Loc.GetString("god-selection-cthulhu-button"),
                1 => Loc.GetString("god-selection-honk-mother-button"),
                2 => Loc.GetString("god-selection-technomium-button"),
                3 => Loc.GetString("god-selection-gray-wave-button"),
                _ => "",
            };
        }
    }
}
