using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Content.Client.Imperial.CustomChaplain.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GodSelectionWindow : DefaultWindow
    {
        private readonly Dictionary<string, int> _clickCounts = new();
        private readonly Dictionary<string, Button> _buttons = new();
        private float _resetTime = 0f;
        private bool _timerActive = false;

        public event Action<string, bool>? OnGodSelected;



        public GodSelectionWindow()
        {
            RobustXamlLoader.Load(this);

            // Initialize button references from XAML
            _buttons["Ктулху"] = CthulhuButton;
            _buttons["Хонкоматерь"] = HonkMotherButton;
            _buttons["Техномиум"] = TechnomiumButton;
            _buttons["Серая волна"] = GrayWaveButton;
            _buttons["Custom"] = CustomGodButton;

            // Initialize click tracking
            foreach (var button in _buttons.Keys)
            {
                _clickCounts[button] = 0;
            }

            // Subscribe to button events
            CthulhuButton.OnPressed += _ => HandleGodSelection("Ктулху", false);
            HonkMotherButton.OnPressed += _ => HandleGodSelection("Хонкоматерь", false);
            TechnomiumButton.OnPressed += _ => HandleGodSelection("Техномиум", false);
            GrayWaveButton.OnPressed += _ => HandleGodSelection("Серая волна", false);
            CustomGodButton.OnPressed += _ => OnCustomGodClicked();

            // Subscribe to window closing event - this is the key fix
            this.OnClose += OnWindowClosing;
        }

        private void OnWindowClosing()
        {
            ResetAllCounters();
        }

        private void OnCustomGodClicked()
        {
            var customName = CustomGodTextBox.Text?.Trim();
            if (string.IsNullOrEmpty(customName))
            {
                StatusText.Text = "Введите имя вашего бога";
                _clickCounts["Custom"] = 0;
                RestoreButtonToOriginal("Custom");
                return;
            }

            HandleGodSelection(customName, true);
        }

        private void HandleGodSelection(string godName, bool isCustom)
        {
            if (string.IsNullOrEmpty(godName?.Trim()))
            {
                StatusText.Text = "Введите корректное имя бога";
                if (isCustom)
                {
                    _clickCounts["Custom"] = 0;
                    RestoreButtonToOriginal("Custom");
                }
                return;
            }

            var key = isCustom ? "Custom" : godName;
            _clickCounts[key]++;

            if (_clickCounts[key] == 1)
            {
                // First click - change button to confirmation mode
                ChangeButtonToConfirmation(key, godName);

                // Reset other counters and restore their buttons
                foreach (var otherKey in _clickCounts.Keys.Where(k => k != key))
                {
                    if (_clickCounts[otherKey] > 0)
                    {
                        _clickCounts[otherKey] = 0;
                        RestoreButtonToOriginal(otherKey);
                    }
                }

                // Start auto-reset timer
                StartAutoResetTimer();
            }
            else if (_clickCounts[key] == 2)
            {
                // Confirmed selection
                OnGodSelected?.Invoke(godName, isCustom);
                this.Close();
            }
        }

                        private void StartAutoResetTimer()
        {
            _resetTime = 10.0f; // 10 seconds
            _timerActive = true;

            // TODO: Implement auto-reset timer if needed
            // For now, buttons will reset only when window closes or user selects another god
        }

        private void AutoResetAllCounters()
        {
            _timerActive = false;
            _resetTime = 0f;

            foreach (var key in _clickCounts.Keys)
            {
                _clickCounts[key] = 0;
                RestoreButtonToOriginal(key);
            }
            StatusText.Text = "Нажмите на кнопку дважды для подтверждения";
        }

        private void ResetAllCounters()
        {
            _timerActive = false;
            _resetTime = 0f;

            foreach (var key in _clickCounts.Keys)
            {
                _clickCounts[key] = 0;
                RestoreButtonToOriginal(key);
            }
            StatusText.Text = "Нажмите на кнопку дважды для подтверждения";
        }

        private void ChangeButtonToConfirmation(string key, string godName)
        {
            if (_buttons.TryGetValue(key, out var button))
            {
                button.Text = $"Нажмите второй раз для подтверждения: {godName}";
                button.Modulate = new Color(1.0f, 0.3f, 0.3f); // Red color
            }
        }

        private void RestoreButtonToOriginal(string key)
        {
            if (_buttons.TryGetValue(key, out var button))
            {
                button.Text = GetOriginalButtonText(key);
                button.Modulate = Color.White; // White color
            }
        }

        private string GetOriginalButtonText(string key)
        {
            return key switch
            {
                "Ктулху" => "Ктулху",
                "Хонкоматерь" => "Хонкоматерь",
                "Техномиум" => "Техномиум",
                "Серая волна" => "Серая волна",
                "Custom" => "Создать",
                _ => key
            };
        }
    }
}

