using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Lavaland.LavalandShuttle;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Lavaland.LavalandShuttle.UI;

[GenerateTypedNameReferences]
public sealed partial class LavalandShuttleConsoleWindow : FancyWindow
{
    public event Action? OnSelectStation;
    public event Action? OnSelectLavaland;
    public event Action? OnDepart;

    public LavalandShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("lavaland-shuttle-console-window-title");

        FlyToStationButton.Text = Loc.GetString("lavaland-shuttle-console-fly-station");
        FlyToLavalandButton.Text = Loc.GetString("lavaland-shuttle-console-fly-lavaland");
        DepartButton.Text = Loc.GetString("lavaland-shuttle-console-depart");

        FlyToStationButton.OnPressed += _ => OnSelectStation?.Invoke();
        FlyToLavalandButton.OnPressed += _ => OnSelectLavaland?.Invoke();
        DepartButton.OnPressed += _ => OnDepart?.Invoke();
    }

    public void UpdateState(LavalandShuttleConsoleBoundUserInterfaceState state)
    {
        FlyToStationButton.Disabled = !state.StationAvailable;
        FlyToLavalandButton.Disabled = !state.LavalandAvailable;
        DepartButton.Disabled = !state.CanDepart;

        DestinationLabel.Text = state.SelectedDestination switch
        {
            LavalandShuttleDestination.Station  => Loc.GetString("lavaland-shuttle-console-destination-station"),
            LavalandShuttleDestination.Lavaland => Loc.GetString("lavaland-shuttle-console-destination-lavaland"),
            _                                   => Loc.GetString("lavaland-shuttle-console-destination-none"),
        };
    }
}
