using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics; // Imperial Weekly Mode
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CargoShuttleMenu : FancyWindow
    {
        public CargoShuttleMenu()
        {
            RobustXamlLoader.Load(this);
            Title = Loc.GetString("cargo-shuttle-console-menu-title");
        }

        public void SetAccountName(string name)
        {
            AccountNameLabel.Text = name;
        }

        public void SetShuttleName(string name)
        {
            ShuttleNameLabel.Text = name;
        }

        public void SetOrders(SpriteSystem sprites, IPrototypeManager protoManager, List<CargoOrderData> orders)
        {
            Orders.RemoveAllChildren();

            foreach (var order in orders)
            {
                 // Imperial Weekly Mode: Original code removed:
                 // if (!protoManager.Resolve(order.Product, out var productProto))
                 //     continue;
                 //
                 // var product = protoManager.Index<EntityPrototype>(productProto.Product);
                 // var productName = product.Name;
                 // Imperial Weekly Mode Start
                 string productName;
                 Texture? icon;

                 if (order.WeeklyProduct is { } weeklyProduct)
                 {
                     productName = weeklyProduct.Name;
                     icon = sprites.Frame0(weeklyProduct.Icon);
                 }
                 else
                 {
                     if (!protoManager.Resolve<CargoProductPrototype>(order.Product, out var productProto))
                         continue;

                     var product = protoManager.Index<EntityPrototype>(productProto.Product);
                     productName = product.Name;
                     icon = sprites.Frame0(product);
                 }
                 // Imperial Weekly Mode End

                 var account = protoManager.Index(order.Account);

                 var row = new CargoOrderRow
                 {
                     Order = order,
                     // Imperial Weekly Mode: Original code removed:
                     // Icon = { Texture = sprites.Frame0(product) },
                     // Imperial Weekly Mode
                     Icon = { Texture = icon },
                     ProductName =
                     {
                         Text = Loc.GetString(
                             "cargo-console-menu-populate-orders-cargo-order-row-product-name-text",
                             ("productName", productName),
                             ("orderAmount", order.OrderQuantity - order.NumDispatched),
                             ("orderRequester", order.Requester),
                             ("accountColor", account.Color),
                             ("account", Loc.GetString(account.Code)))
                     },
                     Description = {Text = Loc.GetString("cargo-console-menu-order-reason-description",
                         ("reason", order.Reason))}
                 };

                 row.Approve.Visible = false;
                 row.Cancel.Visible = false;

                 Orders.AddChild(row);
            }
        }
    }
}
