using System.Linq;
using Content.Client.Cargo.Systems;
using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CargoConsoleMenu : FancyWindow
    {
        [Dependency] private readonly IGameTiming _timing = default!;

        private readonly IEntityManager _entityManager;
        private readonly IPrototypeManager _protoManager;
        private readonly CargoSystem _cargoSystem;
        private readonly SpriteSystem _spriteSystem;
        private EntityUid _owner;
        private EntityUid? _station;

        private readonly EntityQuery<CargoOrderConsoleComponent> _orderConsoleQuery;
        private readonly EntityQuery<StationBankAccountComponent> _bankQuery;

        public event Action<CargoProductRow?>? OnItemSelected;
        public event Action<CargoOrderData?>? OnOrderApproved;
        public event Action<CargoOrderData?>? OnOrderCanceled;

        public event Action<ProtoId<CargoAccountPrototype>?, int>? OnAccountAction;

        public event Action<ButtonEventArgs>? OnToggleUnboundedLimit;

        private readonly List<string> _categoryStrings = new();
        private string? _category;

        public List<ProtoId<CargoProductPrototype>> ProductCatalogue = new();

        public CargoConsoleMenu(EntityUid owner, IEntityManager entMan, IPrototypeManager protoManager, SpriteSystem spriteSystem)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _entityManager = entMan;
            _protoManager = protoManager;
            _cargoSystem = entMan.System<CargoSystem>();
            _spriteSystem = spriteSystem;
            _owner = owner;

            _orderConsoleQuery = _entityManager.GetEntityQuery<CargoOrderConsoleComponent>();
            _bankQuery = _entityManager.GetEntityQuery<StationBankAccountComponent>();

            Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

            SearchBar.OnTextChanged += OnSearchBarTextChanged;
            Categories.OnItemSelected += OnCategoryItemSelected;

            if (entMan.TryGetComponent<CargoOrderConsoleComponent>(owner, out var orderConsole))
            {
                var accountProto = _protoManager.Index(orderConsole.Account);
                AccountNameLabel.Text = Loc.GetString("cargo-console-menu-account-name-format",
                    ("color", accountProto.Color),
                    ("name", Loc.GetString(accountProto.Name)),
                    ("code", Loc.GetString(accountProto.Code)));
            }

            TabContainer.SetTabTitle(0, Loc.GetString("cargo-console-menu-tab-title-orders"));
            TabContainer.SetTabTitle(1, Loc.GetString("cargo-console-menu-tab-title-funds"));

            ActionOptions.OnItemSelected += idx =>
            {
                ActionOptions.SelectId(idx.Id);
            };

            TransferSpinBox.IsValid = val =>
            {
                if (!_entityManager.TryGetComponent<CargoOrderConsoleComponent>(owner, out var console) ||
                    !_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
                    return true;

                return val >= 0 && val <= (int) (console.TransferLimit * bank.Accounts[console.Account]);
            };

            AccountActionButton.OnPressed += _ =>
            {
                var account = (ProtoId<CargoAccountPrototype>?) ActionOptions.SelectedMetadata;
                OnAccountAction?.Invoke(account, TransferSpinBox.Value);
            };

            AccountLimitToggleButton.OnPressed += a =>
            {
                OnToggleUnboundedLimit?.Invoke(a);
            };
        }

        private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            SetCategoryText(args.Id);
            PopulateProducts();
        }

        private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
        {
            PopulateProducts();
        }

        private void SetCategoryText(int id)
        {
            _category = id == 0 ? null : _categoryStrings[id];
            Categories.SelectId(id);
        }

        private IEnumerable<CargoProductPrototype> ProductPrototypes
        {
            get
            {
                var allowedGroups = _entityManager.GetComponentOrNull<CargoOrderConsoleComponent>(_owner)?.AllowedGroups;

                foreach (var cargoPrototypeId in ProductCatalogue)
                {
                    var cargoPrototype = _protoManager.Index(cargoPrototypeId);

                    if (!allowedGroups?.Contains(cargoPrototype.Group) ?? false)
                        continue;

                    yield return cargoPrototype;
                }
            }
        }

        /// <summary>
        ///     Populates the list of products that will actually be shown, using the current filters.
        /// </summary>
        public void PopulateProducts()
        {
            Products.RemoveAllChildren();
            // Imperial Weekly Mode: Original code removed:
            // var products = ProductPrototypes.ToList();
            // products.Sort((x, y) =>
            //     string.Compare(x.Name, y.Name, StringComparison.CurrentCultureIgnoreCase));
            // foreach (var prototype in products)
            // search.Length != 0 && prototype.Name.ToLowerInvariant().Contains(search) ||
            // search.Length != 0 && prototype.Description.ToLowerInvariant().Contains(search) ||
            // search.Length == 0 && _category != null && Loc.GetString(prototype.Category).Equals(_category)
            // Product = prototype,
            // ProductName = { Text = prototype.Name },
            // MainButton = { ToolTip = prototype.Description },
            // PointCost = { Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", prototype.Cost.ToString())) },
            // Icon = { Texture = _spriteSystem.Frame0(prototype.Icon) },
            // Imperial Weekly Mode Start
            var products = GetProductDisplayData();

            var search = SearchBar.Text.Trim().ToLowerInvariant();
            foreach (var product in products)
            {
                // if no search or category
                // else if search
                // else if category and not search
                if (search.Length == 0 && _category == null ||
                    // Imperial Weekly Mode
                    search.Length != 0 && product.Name.ToLowerInvariant().Contains(search) ||
                    search.Length != 0 && product.Description.ToLowerInvariant().Contains(search) ||
                    search.Length == 0 && _category != null && product.Category.Equals(_category))
                {
                    var button = new CargoProductRow
                    {
                        // Imperial Weekly Mode
                        Product = product.Product,
                        WeeklyProduct = product.WeeklyProduct,
                        ProductId = product.ProductId,
                        ProductName = { Text = product.Name },
                        MainButton = { ToolTip = product.Description },
                        PointCost = { Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", product.Cost.ToString())) },
                        Icon = { Texture = _spriteSystem.Frame0(product.Icon) },
                    };
                    button.MainButton.OnPressed += args =>
                    {
                        OnItemSelected?.Invoke(button);
                    };
                    Products.AddChild(button);
                }
            }
            // Imperial Weekly Mode End
        }

        /// <summary>
        ///     Populates the list of products that will actually be shown, using the current filters.
        /// </summary>
        public void PopulateCategories()
        {
            _categoryStrings.Clear();
            Categories.Clear();

            // Imperial Weekly Mode: Original code removed:
            // foreach (var prototype in ProductPrototypes)
            // {
            //     if (!_categoryStrings.Contains(Loc.GetString(prototype.Category)))
            //     {
            //         _categoryStrings.Add(Loc.GetString(prototype.Category));
            //     }
            // }
            // Imperial Weekly Mode Start
            foreach (var product in GetProductDisplayData())
            {
                if (!_categoryStrings.Contains(product.Category))
                {
                    _categoryStrings.Add(product.Category);
                }
            }

            _categoryStrings.Sort();

            // Imperial Weekly Mode
            if (_category != null && !_categoryStrings.Contains(_category))
                _category = null;

            // Add "All" category at the top of the list
            _categoryStrings.Insert(0, Loc.GetString("cargo-console-menu-populate-categories-all-text"));

            foreach (var str in _categoryStrings)
            {
                Categories.AddItem(str);
            }

            var selected = _category == null ? 0 : _categoryStrings.IndexOf(_category);
            Categories.SelectId(Math.Max(0, selected));
            // Imperial Weekly Mode End
        }

        /// <summary>
        ///     Populates the list of orders and requests.
        /// </summary>
        public void PopulateOrders(IEnumerable<CargoOrderData> orders)
        {
            if (!_orderConsoleQuery.TryComp(_owner, out var orderConsole))
                return;

            Requests.RemoveAllChildren();

            foreach (var order in orders)
            {
                // Imperial Weekly Mode: Original code removed:
                // if (order.Approved || !_protoManager.Resolve(order.Product, out var productProto))
                //     continue;
                //
                // var product = _protoManager.Index<EntityPrototype>(productProto.Product);
                // var productName = productProto.Name;
                // Imperial Weekly Mode Start
                if (order.Approved)
                    continue;

                string productName;
                int productCost;
                Texture? icon;

                if (order.WeeklyProduct is { } weeklyProduct)
                {
                    productName = weeklyProduct.Name;
                    productCost = weeklyProduct.Cost;
                    icon = _spriteSystem.Frame0(weeklyProduct.Icon);
                }
                else
                {
                    if (!_protoManager.Resolve<CargoProductPrototype>(order.Product, out var productProto))
                        continue;

                    var product = _protoManager.Index<EntityPrototype>(productProto.Product);
                    productName = productProto.Name;
                    productCost = productProto.Cost;
                    icon = _spriteSystem.Frame0(product);
                }
                // Imperial Weekly Mode End

                var requester = !string.IsNullOrEmpty(order.Requester) ?
                    order.Requester : Loc.GetString("cargo-console-menu-order-row-alerts-requester-unknown");
                var account = _protoManager.Index(order.Account);

                var row = new CargoOrderRow
                {
                    Order = order,

                    Title =
                    {
                        Text = Loc.GetString(
                            "cargo-console-menu-order-row-title",
                            ("productName", productName),
                            ("orderAmount", order.OrderQuantity),
                            // Imperial Weekly Mode: Original code removed:
                            // ("orderPrice", productProto.Cost)),
                            ("orderPrice", productCost)),
                    },

                    Stride =
                    {
                        PanelOverride = new StyleBoxFlat
                        {
                            BackgroundColor = account.Color,
                            ContentMarginBottomOverride = 2,
                        },
                    },

                    // Imperial Weekly Mode: Original code removed:
                    // Icon = { Texture = _spriteSystem.Frame0(product) },
                    // Imperial Weekly Mode
                    Icon = { Texture = icon },

                    ProductName =
                    {
                        Text = Loc.GetString(
                            "cargo-console-menu-populate-orders-cargo-order-row-product-name-text",
                            ("orderRequester", requester),
                            ("accountColor", account.Color),
                            ("account", Loc.GetString(account.Code)))
                    },

                    Description =
                    {
                        Text = !string.IsNullOrEmpty(order.Reason) ?
                            Loc.GetString(
                                "cargo-console-menu-order-row-product-description",
                                ("orderReason", order.Reason))
                        :
                            Loc.GetString(
                                "cargo-console-menu-order-row-product-description",
                                ("orderReason", Loc.GetString("cargo-console-menu-order-row-alerts-reason-absent")))
                    }
                };

                row.Cancel.OnPressed += (args) => { OnOrderCanceled?.Invoke(order); };

                // TODO: Disable based on access.
                row.SetApproveVisible(orderConsole.Mode != CargoOrderConsoleMode.SendToPrimary);
                row.Approve.OnPressed += (args) => { OnOrderApproved?.Invoke(order); };
                Requests.AddChild(row);
            }
        }

        public void PopulateAccountActions()
        {
            if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank) ||
                !_entityManager.TryGetComponent<CargoOrderConsoleComponent>(_owner, out var console))
                return;

            var i = 0;
            ActionOptions.Clear();
            ActionOptions.AddItem(Loc.GetString("cargo-console-menu-account-action-option-withdraw"), i);
            i++;
            foreach (var account in bank.Accounts.Keys)
            {
                if (account == console.Account)
                    continue;
                var accountProto = _protoManager.Index(account);
                ActionOptions.AddItem(Loc.GetString("cargo-console-menu-account-action-option-transfer",
                    ("code", Loc.GetString(accountProto.Code))),
                    i);
                ActionOptions.SetItemMetadata(i, account);
                i++;
            }
        }

        public void UpdateStation(EntityUid station)
        {
            _station = station;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (!_bankQuery.TryComp(_station, out var bankAccount) ||
                !_orderConsoleQuery.TryComp(_owner, out var orderConsole))
            {
                return;
            }

            var balance = _cargoSystem.GetBalanceFromAccount((_station.Value, bankAccount), orderConsole.Account);
            PointsLabel.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", balance));
            TransferLimitLabel.Text = Loc.GetString("cargo-console-menu-account-action-transfer-limit",
                ("limit", (int) (balance * orderConsole.TransferLimit)));

            UnlimitedNotifier.Visible = orderConsole.TransferUnbounded;
            AccountActionButton.Disabled = TransferSpinBox.Value <= 0 ||
                                           TransferSpinBox.Value > bankAccount.Accounts[orderConsole.Account] * orderConsole.TransferLimit ||
                                           _timing.CurTime < orderConsole.NextAccountActionTime;

            RightPart.Visible = orderConsole.Mode != CargoOrderConsoleMode.PrintSlip;
        }
    }
}
