- type: job
  id: Clown
  name: job-name-clown
  description: job-description-clown
  playTimeTracker: JobClown
  startingGear: ClownGear
  icon: "JobIconClown"
  supervisors: objective-issuer-honk
  canBeAntag: false
  # Imperial Rofls
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: CrewSkills
      skills:
      - skillBotany #base
      - skillBaseMed
      - skillBaseConstraction
      - skillPiloting #Hard
      - skillShooting

- type: startingGear
  id: ClownGear
  equipment:
    mask: ClothingMaskClownSecurity
    pocket1: BikeHorn
    pocket2: ClownRecorder
    id: HoSPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampClown
    - CrayonRainbow
