- type: parallax
  id: TrainStation
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/AspidParallaxBG.png"
      slowness: 0.998046875
      scale: "1, 1"
