using System.Text;
using Content.Shared.Imperial.DeimonFly.DeathNote;
using Content.Shared.Imperial.DeimonFly.DeathNote.Models;
using Content.Shared.Imperial.DeimonFly.DeathNote.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.DeimonFly.DeathNote.UI;

[GenerateTypedNameReferences]
public sealed partial class DeathNoteAdminLedgerWindow : DefaultWindow
{
    private int _page;
    private int _pageCount = 1;
    private bool _requestPending;

    public event Action<int>? OnPageRequested;

    public DeathNoteAdminLedgerWindow()
    {
        RobustXamlLoader.Load(this);

        PreviousButton.OnPressed += _ => RequestPage(Math.Max(0, _page - 1));
        NextButton.OnPressed += _ => RequestPage(Math.Min(_pageCount - 1, _page + 1));
        RefreshButton.OnPressed += _ => RequestPage(_page);
        UpdateButtons();
    }

    public void UpdatePage(DeathNoteAdminPageResponseMessage response)
    {
        _page = response.Page;
        _pageCount = Math.Max(1, response.PageCount);
        _requestPending = false;
        RequestStatusLabel.Text = string.Empty;
        SummaryLabel.Text = Loc.GetString("death-note-admin-summary", ("count", response.TotalEntries));
        UpdateButtons();
        PageLabel.Text = Loc.GetString(
            "death-note-ui-page-number",
            ("page", _page + 1),
            ("count", _pageCount));

        if (response.Entries.Length == 0)
        {
            EntriesText.SetMessage(Loc.GetString("death-note-admin-no-records"));
            return;
        }

        var builder = new StringBuilder();
        foreach (var entry in response.Entries)
        {
            AppendEntry(builder, entry);
            builder.AppendLine();
        }

        EntriesText.SetMessage(builder.ToString().TrimEnd());
    }

    private void RequestPage(int page)
    {
        if (_requestPending || OnPageRequested == null)
            return;

        _requestPending = true;
        RequestStatusLabel.Text = Loc.GetString("death-note-admin-loading");
        UpdateButtons();
        OnPageRequested.Invoke(page);
    }

    private void UpdateButtons()
    {
        PreviousButton.Disabled = _requestPending || _page <= 0;
        NextButton.Disabled = _requestPending || _page >= _pageCount - 1;
        RefreshButton.Disabled = _requestPending;
    }

    private static void AppendEntry(StringBuilder builder, DeathNoteAdminEntry entry)
    {
        builder.Append('#').Append(entry.EntryId)
            .Append(" | ").Append(FormatRoundTime(entry.CreatedRoundTime))
            .Append(" -> ").Append(FormatRoundTime(entry.ScheduledRoundTime)).AppendLine()
            .Append(Loc.GetString("death-note-admin-page-line")).Append(": ")
            .Append(entry.PageIndex >= 0 ? (entry.PageIndex + 1).ToString() : "—")
            .Append(" / ")
            .Append(entry.LineIndex >= 0 ? (entry.LineIndex + 1).ToString() : "—").AppendLine()
            .Append(Loc.GetString("death-note-admin-writer")).Append(": ").Append(entry.Writer).AppendLine()
            .Append(Loc.GetString("death-note-admin-owner")).Append(": ").Append(entry.Owner).AppendLine()
            .Append(Loc.GetString("death-note-admin-notebook")).Append(": ").Append(entry.Notebook).AppendLine()
            .Append(Loc.GetString("death-note-admin-entered-name")).Append(": ").Append(entry.EnteredTargetName).AppendLine()
            .Append(Loc.GetString("death-note-admin-target")).Append(": ").Append(entry.ResolvedTarget).AppendLine()
            .Append(Loc.GetString("death-note-admin-cause")).Append(": ").Append(entry.CauseText).AppendLine()
            .Append(Loc.GetString("death-note-admin-preset")).Append(": ").Append(entry.PresetId).AppendLine()
            .Append(Loc.GetString("death-note-admin-destruction")).Append(": ")
            .Append(GetDestructionText(entry.Destruction)).AppendLine()
            .Append(Loc.GetString("death-note-admin-status")).Append(": ")
            .Append(GetStatusText(entry.Status))
            .Append(" / ")
            .Append(GetFailureReasonText(entry.FailureReason))
            .AppendLine()
            .Append(Loc.GetString("death-note-admin-effect-state")).Append(": ")
            .Append(Loc.GetString(entry.EffectStarted
                ? "death-note-admin-state-started"
                : "death-note-admin-state-not-started")).AppendLine()
            .Append(Loc.GetString("death-note-admin-death-state")).Append(": ")
            .Append(Loc.GetString(entry.DeathConfirmed
                ? "death-note-admin-state-confirmed"
                : "death-note-admin-state-not-confirmed")).AppendLine()
            .Append(Loc.GetString("death-note-admin-result")).Append(": ").Append(entry.Result).AppendLine()
            .Append(Loc.GetString("death-note-admin-error")).Append(": ").Append(entry.Error).AppendLine();
    }

    private static string GetDestructionText(DeathNoteDestructionLevel? destruction)
    {
        var locId = destruction switch
        {
            DeathNoteDestructionLevel.Minimal => "death-note-admin-destruction-minimal",
            DeathNoteDestructionLevel.Low => "death-note-admin-destruction-low",
            DeathNoteDestructionLevel.Moderate => "death-note-admin-destruction-moderate",
            DeathNoteDestructionLevel.High => "death-note-admin-destruction-high",
            DeathNoteDestructionLevel.Extreme => "death-note-admin-destruction-extreme",
            _ => "death-note-admin-destruction-unknown",
        };

        return Loc.GetString(locId);
    }

    private static string GetStatusText(DeathNoteEntryStatus status)
    {
        var locId = status switch
        {
            DeathNoteEntryStatus.Submitted => "death-note-admin-entry-status-submitted",
            DeathNoteEntryStatus.Scheduled => "death-note-admin-entry-status-scheduled",
            DeathNoteEntryStatus.CustomDelivered => "death-note-admin-entry-status-custom-delivered",
            DeathNoteEntryStatus.Executing => "death-note-admin-entry-status-executing",
            DeathNoteEntryStatus.EffectStarted => "death-note-admin-entry-status-effect-started",
            DeathNoteEntryStatus.DeathConfirmed => "death-note-admin-entry-status-death-confirmed",
            DeathNoteEntryStatus.Failed => "death-note-admin-entry-status-failed",
            DeathNoteEntryStatus.TargetMissing => "death-note-admin-entry-status-target-missing",
            DeathNoteEntryStatus.TargetAlreadyDead => "death-note-admin-entry-status-target-already-dead",
            DeathNoteEntryStatus.AmbiguousName => "death-note-admin-entry-status-ambiguous-name",
            DeathNoteEntryStatus.InvalidFormat => "death-note-admin-entry-status-invalid-format",
            DeathNoteEntryStatus.Cancelled => "death-note-admin-entry-status-cancelled",
            _ => "death-note-admin-entry-status-unknown",
        };

        return Loc.GetString(locId);
    }

    private static string GetFailureReasonText(DeathNoteFailureReason reason)
    {
        var locId = reason switch
        {
            DeathNoteFailureReason.None => "death-note-admin-failure-none",
            DeathNoteFailureReason.TargetMissing => "death-note-admin-failure-target-missing",
            DeathNoteFailureReason.TargetAlreadyDead => "death-note-admin-failure-target-already-dead",
            DeathNoteFailureReason.TargetDeleted => "death-note-admin-failure-target-deleted",
            DeathNoteFailureReason.TargetNoLongerAlive => "death-note-admin-failure-target-no-longer-alive",
            DeathNoteFailureReason.AmbiguousName => "death-note-admin-failure-ambiguous-name",
            DeathNoteFailureReason.InvalidFormat => "death-note-admin-failure-invalid-format",
            DeathNoteFailureReason.InvalidName => "death-note-admin-failure-invalid-name",
            DeathNoteFailureReason.InvalidTime => "death-note-admin-failure-invalid-time",
            DeathNoteFailureReason.TimeInPast => "death-note-admin-failure-time-in-past",
            DeathNoteFailureReason.TimeTooSoon => "death-note-admin-failure-time-too-soon",
            DeathNoteFailureReason.UnknownPreset => "death-note-admin-failure-unknown-preset",
            DeathNoteFailureReason.NameTooLong => "death-note-admin-failure-name-too-long",
            DeathNoteFailureReason.CauseTooLong => "death-note-admin-failure-cause-too-long",
            DeathNoteFailureReason.InvalidPage => "death-note-admin-failure-invalid-page",
            DeathNoteFailureReason.PageFull => "death-note-admin-failure-page-full",
            DeathNoteFailureReason.EntryLimitReached => "death-note-admin-failure-entry-limit-reached",
            DeathNoteFailureReason.Cooldown => "death-note-admin-failure-cooldown",
            DeathNoteFailureReason.Replay => "death-note-admin-failure-replay",
            DeathNoteFailureReason.NoPen => "death-note-admin-failure-no-pen",
            DeathNoteFailureReason.AccessDenied => "death-note-admin-failure-access-denied",
            DeathNoteFailureReason.HandlerError => "death-note-admin-failure-handler-error",
            DeathNoteFailureReason.RoundEnded => "death-note-admin-failure-round-ended",
            DeathNoteFailureReason.TechnicalError => "death-note-admin-failure-technical-error",
            _ => "death-note-admin-failure-unknown",
        };

        return Loc.GetString(locId);
    }

    private static string FormatRoundTime(TimeSpan time)
    {
        return $"{(int) time.TotalHours:00}:{time.Minutes:00}:{time.Seconds:00}";
    }
}
