using System.Collections.Immutable;
using System.Linq;
using Content.Shared.Imperial.DeimonFly.DeathNote;
using Content.Shared.Imperial.DeimonFly.DeathNote.Models;
using Content.Shared.Imperial.DeimonFly.DeathNote.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.DeimonFly.DeathNote.UI;

/// <summary>
/// Физические развороты: чёрный форзац правил и тридцать белых страниц.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DeathNoteWindow : DefaultWindow
{
    private readonly Dictionary<int, DeathNotePageDraft> _drafts = new();
    private readonly Dictionary<int, string> _feedback = new();
    private DeathNoteBoundUserInterfaceState? _state;
    private ImmutableArray<DeathNoteNotebookSpread> _spreads = ImmutableArray<DeathNoteNotebookSpread>.Empty;
    private uint _revision = 1;
    private int _spreadIndex;
    private int? _pendingPageIndex;
    private int? _focusAfterAcceptedPage;
    private bool _serverCanSubmit;
    private bool _spreadRequestPending;

    public event Action<int, string, uint>? OnSubmit;
    public event Action<int>? OnSpreadRequested;

    public DeathNoteWindow()
    {
        RobustXamlLoader.Load(this);

        LeftBlankSheet.PanelOverride = DeathNotePaperStyle.Create();
        RightBlankSheet.PanelOverride = DeathNotePaperStyle.Create();
        PreviousButton.OnPressed += _ => RequestSpread(_spreadIndex - 1);
        NextButton.OnPressed += _ => RequestSpread(_spreadIndex + 1);
        LeftWritableSheet.OnSubmit += Submit;
        RightWritableSheet.OnSubmit += Submit;
    }

    public void UpdateState(DeathNoteBoundUserInterfaceState state)
    {
        SaveVisibleDrafts(_focusAfterAcceptedPage);
        _state = state;
        _revision = state.SubmissionRevision;
        _serverCanSubmit = state.CanSubmit;
        _spreads = DeathNotePagination.Build(state.WritablePageCount);
        _spreadIndex = DeathNotePagination.ClampSpreadIndex(state.SpreadIndex, _spreads.Length);
        _spreadRequestPending = false;
        RenderSpread();

        if (_focusAfterAcceptedPage is { } page)
        {
            FocusPageInput(page);
            _focusAfterAcceptedPage = null;
        }
    }

    public void ShowFeedback(DeathNoteSubmissionResponseMessage response)
    {
        _revision = response.NextRevision;
        var pageIndex = _pendingPageIndex;
        _pendingPageIndex = null;

        if (pageIndex == null)
            return;

        if (response.Feedback == DeathNoteSubmissionFeedback.Accepted)
        {
            _drafts.Remove(pageIndex.Value);
            _feedback.Remove(pageIndex.Value);
            _focusAfterAcceptedPage = pageIndex.Value;
            return;
        }

        _feedback[pageIndex.Value] = Loc.GetString(FeedbackLocId(response.Feedback));
        RenderSpread();
        FocusPageInput(pageIndex.Value);
    }

    private void Submit(int pageIndex, DeathNotePageDraft draft)
    {
        if (_pendingPageIndex != null || _spreadRequestPending)
            return;

        _drafts[pageIndex] = draft;
        _feedback.Remove(pageIndex);
        _pendingPageIndex = pageIndex;
        RenderSpread();
        OnSubmit?.Invoke(pageIndex, draft.EntryText, _revision);
    }

    private void RequestSpread(int requestedSpread)
    {
        if (_state == null ||
            _spreads.Length == 0 ||
            _pendingPageIndex != null ||
            _spreadRequestPending ||
            OnSpreadRequested == null)
        {
            return;
        }

        requestedSpread = DeathNotePagination.ClampSpreadIndex(requestedSpread, _spreads.Length);
        if (requestedSpread == _spreadIndex)
            return;

        SaveVisibleDrafts();
        _spreadRequestPending = true;
        RenderSpread();
        OnSpreadRequested.Invoke(requestedSpread);
    }

    private void SaveVisibleDrafts(int? excludedPageIndex = null)
    {
        SaveDraft(LeftWritableSheet, excludedPageIndex);
        SaveDraft(RightWritableSheet, excludedPageIndex);
    }

    private void SaveDraft(DeathNoteWritablePage sheet, int? excludedPageIndex)
    {
        if (sheet.Visible &&
            sheet.PageIndex >= 0 &&
            sheet.PageIndex != excludedPageIndex)
        {
            _drafts[sheet.PageIndex] = sheet.GetDraft();
        }
    }

    private void RenderSpread()
    {
        if (_state == null || _spreads.Length == 0)
            return;

        _spreadIndex = DeathNotePagination.ClampSpreadIndex(_spreadIndex, _spreads.Length);
        var spread = _spreads[_spreadIndex];
        var navigationDisabled = _pendingPageIndex != null || _spreadRequestPending;
        PreviousButton.Disabled = navigationDisabled ||
                                  !DeathNotePagination.CanGoPrevious(_spreadIndex, _spreads.Length);
        NextButton.Disabled = navigationDisabled ||
                              !DeathNotePagination.CanGoNext(_spreadIndex, _spreads.Length);
        SpreadNumberLabel.Text = Loc.GetString(
            "death-note-ui-spread-number",
            ("spread", _spreadIndex + 1),
            ("count", _spreads.Length));

        RenderLeftSheet(spread.Left);
        RenderRightSheet(spread.Right);
    }

    private void RenderLeftSheet(DeathNoteNotebookSheet sheet)
    {
        RulesSheet.Visible = sheet.Kind == DeathNoteNotebookSheetKind.Rules;
        LeftWritableSheet.Visible = sheet.Kind == DeathNoteNotebookSheetKind.Writable;
        LeftBlankSheet.Visible = sheet.Kind == DeathNoteNotebookSheetKind.Blank;

        if (sheet.Kind == DeathNoteNotebookSheetKind.Rules && _state != null)
        {
            var ruleLines = Loc.GetString(_state.RulePage)
                .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            var rules = FormattedMessage.EscapeText(string.Join("\n\n", ruleLines));
            RulePageText.SetMessage(
                FormattedMessage.FromMarkupOrThrow(
                    $"[font=\"DeathNoteHandwriting\" size=11][color=#eee7dc]{rules}[/color][/font]"),
                tagsAllowed: null);
            RulePageText.LineHeightScale = 0.95f;
        }
        else if (sheet.Kind == DeathNoteNotebookSheetKind.Writable)
        {
            ShowWritablePage(LeftWritableSheet, sheet.PageIndex);
        }
    }

    private void RenderRightSheet(DeathNoteNotebookSheet sheet)
    {
        RightWritableSheet.Visible = sheet.Kind == DeathNoteNotebookSheetKind.Writable;
        RightBlankSheet.Visible = sheet.Kind == DeathNoteNotebookSheetKind.Blank;

        if (sheet.Kind == DeathNoteNotebookSheetKind.Writable)
            ShowWritablePage(RightWritableSheet, sheet.PageIndex);
    }

    private void ShowWritablePage(DeathNoteWritablePage sheet, int pageIndex)
    {
        if (_state == null)
            return;

        var entries = _state.Entries
            .Where(entry => entry.PageIndex == pageIndex)
            .OrderBy(entry => entry.LineIndex)
            .ToArray();
        _drafts.TryGetValue(pageIndex, out var draft);
        _feedback.TryGetValue(pageIndex, out var feedback);
        sheet.ShowPage(
            pageIndex,
            entries,
            draft,
            _state.MaxEntryTextLength,
            _state.EntriesPerPage,
            _serverCanSubmit,
            _pendingPageIndex != null || _spreadRequestPending,
            feedback ?? string.Empty);
    }

    private void FocusPageInput(int pageIndex)
    {
        if (LeftWritableSheet.Visible && LeftWritableSheet.PageIndex == pageIndex)
            LeftWritableSheet.FocusInput();
        else if (RightWritableSheet.Visible && RightWritableSheet.PageIndex == pageIndex)
            RightWritableSheet.FocusInput();
    }

    private static string FeedbackLocId(DeathNoteSubmissionFeedback feedback)
    {
        return feedback switch
        {
            DeathNoteSubmissionFeedback.Accepted => "death-note-feedback-accepted",
            DeathNoteSubmissionFeedback.InvalidFormat => "death-note-feedback-invalid-format",
            DeathNoteSubmissionFeedback.InvalidName => "death-note-feedback-invalid-name",
            DeathNoteSubmissionFeedback.NameTooLong => "death-note-feedback-name-too-long",
            DeathNoteSubmissionFeedback.CauseTooLong => "death-note-feedback-cause-too-long",
            DeathNoteSubmissionFeedback.InvalidTime => "death-note-feedback-invalid-time",
            DeathNoteSubmissionFeedback.TimeInPast => "death-note-feedback-time-in-past",
            DeathNoteSubmissionFeedback.TimeTooSoon => "death-note-feedback-time-too-soon",
            DeathNoteSubmissionFeedback.UnknownPreset => "death-note-feedback-unknown-preset",
            DeathNoteSubmissionFeedback.InvalidPage => "death-note-feedback-invalid-page",
            DeathNoteSubmissionFeedback.PageFull => "death-note-feedback-page-full",
            DeathNoteSubmissionFeedback.EntryLimitReached => "death-note-feedback-entry-limit",
            DeathNoteSubmissionFeedback.Cooldown => "death-note-feedback-cooldown",
            DeathNoteSubmissionFeedback.NoPen => "death-note-feedback-no-pen",
            DeathNoteSubmissionFeedback.AccessDenied => "death-note-feedback-access-denied",
            DeathNoteSubmissionFeedback.Replay => "death-note-feedback-replay",
            _ => "death-note-feedback-technical-error",
        };
    }
}
