using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.DeimonFly.DeathNote.UI;

[GenerateTypedNameReferences]
public sealed partial class DeathNoteInfluenceWindow : DefaultWindow
{
    public DeathNoteInfluenceWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyDeathNoteStyle();
        SetStaticText();
    }

    public void SetScenario(string scenario, bool isCustomRoleplay)
    {
        var text = isCustomRoleplay
            ? scenario.TrimStart('!', ' ')
            : scenario;
        ScenarioText.SetMessage(
            FormattedMessage.FromMarkupOrThrow(
                $"[font=\"DeathNoteHandwriting\" size=18][color=#eee8dc]{FormattedMessage.EscapeText(text)}[/color][/font]"),
            tagsAllowed: null);
        ScenarioText.LineHeightScale = 1.18f;
    }

    private void ApplyDeathNoteStyle()
    {
        Contents.Margin = new Thickness(0);

        DeathNoteFrame.PanelOverride = CreatePanel(
            "#030303",
            "#b3a173",
            new Thickness(2));
        DeathNoteInnerFrame.PanelOverride = CreatePanel(
            "#000000",
            "#574b31",
            new Thickness(1));
        ScenarioPanel.PanelOverride = CreatePanel(
            "#090806",
            "#8c784c",
            new Thickness(1));
        RulesPanel.PanelOverride = CreatePanel(
            "#070605",
            "#574b31",
            new Thickness(1));
        TitleDivider.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#a18b59"),
        };

        // Стандартная строка заголовка принадлежит RobustToolbox, однако её можно переоформить
        // для этого экземпляра окна, не изменяя общий интерфейс игры.
        var header = FindControl<PanelContainer>("WindowHeader");
        header.PanelOverride = CreatePanel(
            "#050504",
            "#b3a173",
            new Thickness(0, 0, 0, 1));

        var title = FindControl<Label>("TitleLabel");
        title.FontColorOverride = Color.FromHex("#d7c69a");
    }

    private void SetStaticText()
    {
        IntroText.SetMessage(
            CreateHandwrittenText(
                Loc.GetString("death-note-influence-intro"),
                21,
                "#b84d48"));
        IntroText.LineHeightScale = 1.05f;

        ScenarioHeading.SetMessage(
            CreateHandwrittenText(
                Loc.GetString("death-note-influence-scenario"),
                15,
                "#d7c69a"));

        RulesText.SetMessage(
            CreateHandwrittenText(
                Loc.GetString("death-note-influence-rules"),
                13,
                "#aaa18f"));
        RulesText.LineHeightScale = 1.12f;
    }

    private static FormattedMessage CreateHandwrittenText(string text, int size, string color)
    {
        return FormattedMessage.FromMarkupOrThrow(
            $"[font=\"DeathNoteHandwriting\" size={size}][color={color}]{FormattedMessage.EscapeText(text)}[/color][/font]");
    }

    private static StyleBoxFlat CreatePanel(
        string background,
        string border,
        Thickness borderThickness)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = borderThickness,
        };
    }
}
