using System.Numerics;
using Content.Shared.Imperial.DeimonFly.DeathNote.Models;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.DeimonFly.DeathNote.UI;

public readonly record struct DeathNotePageDraft(string EntryText);

/// <summary>
/// Физический белый лист: каждая строка является либо неизменяемой записью,
/// либо единственной областью ввода следующей судьбы.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DeathNoteWritablePage : PanelContainer
{
    private static readonly Color PageTextColor = Color.FromHex("#17120f");
    private static readonly Color PageLineColor = Color.FromHex("#7189a466");
    private static readonly Color MarginLineColor = Color.FromHex("#ad4c4c88");

    private int _pageIndex = -1;
    private int _entriesPerPage = 12;
    private int _maxEntryTextLength = 640;
    private string _draft = string.Empty;
    private LineEdit? _activeInput;

    public event Action<int, DeathNotePageDraft>? OnSubmit;

    public int PageIndex => _pageIndex;

    public DeathNoteWritablePage()
    {
        RobustXamlLoader.Load(this);
        PanelOverride = DeathNotePaperStyle.Create();
    }

    public void ShowPage(
        int pageIndex,
        IReadOnlyList<DeathNotePublicEntry> entries,
        DeathNotePageDraft draft,
        int maxEntryTextLength,
        int entriesPerPage,
        bool serverCanSubmit,
        bool submissionPending,
        string feedback)
    {
        _pageIndex = pageIndex;
        _entriesPerPage = Math.Max(1, entriesPerPage);
        _maxEntryTextLength = Math.Max(1, maxEntryTextLength);
        _draft = draft.EntryText ?? string.Empty;
        _activeInput = null;

        var heading = Loc.GetString("death-note-ui-writable-page-heading", ("page", pageIndex + 1));
        PageHeading.SetMessage(
            FormattedMessage.FromMarkupOrThrow(
                $"[font=\"DeathNoteHandwriting\" size=14][color=#17120f]{FormattedMessage.EscapeText(heading)}[/color][/font]"),
            tagsAllowed: null);

        FeedbackLabel.Text = feedback;
        FeedbackLabel.Visible = !string.IsNullOrWhiteSpace(feedback);
        RenderRows(entries, serverCanSubmit, submissionPending);
    }

    public DeathNotePageDraft GetDraft()
    {
        return new DeathNotePageDraft(_activeInput?.Text ?? _draft);
    }

    public void FocusInput()
    {
        _activeInput?.GrabKeyboardFocus();
    }

    private void RenderRows(
        IReadOnlyList<DeathNotePublicEntry> entries,
        bool serverCanSubmit,
        bool submissionPending)
    {
        EntryRows.RemoveAllChildren();

        for (var lineIndex = 0; lineIndex < _entriesPerPage; lineIndex++)
        {
            var row = new PanelContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                RectClipContent = true,
                MinHeight = 28,
                Margin = new Thickness(30, 0, 4, 0),
            };

            if (lineIndex < entries.Count)
            {
                row.AddChild(CreateWrittenLine(entries[lineIndex]));
            }
            else if (lineIndex == entries.Count && serverCanSubmit && !submissionPending)
            {
                var input = new LineEdit
                {
                    Text = _draft,
                    PlaceHolder = Loc.GetString("death-note-ui-line-placeholder"),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center,
                    ModulateSelfOverride = PageTextColor,
                    StyleClasses = { "PaperLineEdit" },
                    ToolTip = Loc.GetString("death-note-ui-line-tooltip"),
                };
                input.IsValid = text => text.Length <= _maxEntryTextLength;
                input.OnTextChanged += args =>
                {
                    _draft = args.Text;
                    FeedbackLabel.Visible = false;
                };
                input.OnTextEntered += args =>
                {
                    if (!string.IsNullOrWhiteSpace(args.Text) && args.Text.Length <= _maxEntryTextLength)
                        OnSubmit?.Invoke(_pageIndex, new DeathNotePageDraft(args.Text));
                };
                row.AddChild(input);
                _activeInput = input;
            }
            else if (lineIndex == entries.Count && !serverCanSubmit)
            {
                row.ToolTip = Loc.GetString("death-note-feedback-no-pen");
            }

            EntryRows.AddChild(row);
        }
    }

    private RichTextLabel CreateWrittenLine(DeathNotePublicEntry entry)
    {
        // Написанное Кирой является частью ролевой записи. Разобранные поля цели, времени и пресета
        // нужны только серверу для исполнения и не должны изменять видимое предложение.
        var entryText = entry.OriginalText;
        var label = new RichTextLabel
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            StyleClasses = { "PaperWrittenText" },
            ToolTip = entryText,
        };
        label.SetMessage(
            FormattedMessage.FromMarkupOrThrow(
                $"[font=\"DeathNoteHandwriting\" size=12][color=#17120f]{FormattedMessage.EscapeText(entryText)}[/color][/font]"),
            tagsAllowed: null);
        return label;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var top = 38f;
        var bottom = Math.Max(top, PixelHeight - 24f);
        var spacing = (bottom - top) / _entriesPerPage;
        for (var i = 1; i <= _entriesPerPage; i++)
        {
            var y = top + spacing * i;
            handle.DrawLine(new Vector2(0f, y), new Vector2(PixelWidth, y), PageLineColor);
        }

        handle.DrawLine(new Vector2(30f, top), new Vector2(30f, bottom), MarginLineColor);
    }
}
