- type: entity
  id: ActionK9-XSpeed
  name: K9-X
  description: 150#
  components:
  - type: InstantAction
    icon: { sprite: Imperial/electromouse.rsi, state: sm_superspeed}
    event: !type:ElectroMouseSpeedEvent
    useDelay: 20
    itemIconStyle: BigAction
