- type: constructionGraph
  id: GraphK9-X
  start: start
  graph:
  - node: start
    entity: K9-XEndoskeleton
    edges:
    - to: cyborg
      steps:
      - assemblyId: generic
        guideString: K9-X-construction-guide-string

      - tool: Welding
        doAfter: 3

      - material: MetalRod
        amount: 4
        doAfter: 5

      - tool: Welding
        doAfter: 3

      - tag: HudSecurity
        icon:
          sprite: Clothing/Eyes/Hud/sec.rsi
          state: icon
        name: "[color=#05E9E9]Охранный визор[/color]"
        doAfter: 5

      - tool: Screwing
        doAfter: 5

      - material: Steel
        amount: 2
        doAfter: 2

      - material: Cable
        amount: 2
        doAfter: 6
        store: part-container

      - tool: Cutting
        doAfter: 3

      - material: MetalRod
        amount: 16
        doAfter: 5

      - tool: Welding
        doAfter: 4

      - tool: Anchoring
        doAfter: 3

      - tool: Screwing
        doAfter: 5

      - component: Flash
        name: вспышку
        store: part-container
        icon:
          sprite: Objects/Weapons/Melee/flash.rsi
          state: flash

      - tool: Anchoring
        doAfter: 3

  - node: cyborg
    entity: K9-X

  - node: derelictcyborg
    entity: K9-X
